/* ---------------------------------------------------- */

/*  Generated by Enterprise Architect Version 13.5 		*/

/*  Created On : 05-Oct-2021 08:50:24 				*/

/*  DBMS       : SQLite 								*/

/* ---------------------------------------------------- */



/* Drop Tables */



DROP TABLE IF EXISTS 'Building'

;



DROP TABLE IF EXISTS 'HousePipe'

;



DROP TABLE IF EXISTS 'Tree'

;



/* Create Tables with Primary and Foreign Keys, Check and Unique Constraints */



CREATE TABLE 'Building'

(

	'Building_ID' INTEGER NOT NULL PRIMARY KEY,

	'Address' TEXT NULL,

	'NoFloors' INTEGER NULL

)

;



CREATE TABLE 'HousePipe'

(

	'Pipe_ID' INTEGER NOT NULL PRIMARY KEY,

	'Material' TEXT NULL,

	'Building_ID' INTEGER NULL,

	CONSTRAINT 'FK_Building_HousePipe' FOREIGN KEY ('Building_ID') REFERENCES 'Building' ('Building_ID') ON DELETE No Action ON UPDATE No Action

)

;



CREATE TABLE 'Tree'

(

	'Tree_ID' INTEGER NOT NULL PRIMARY KEY,

	'Species' TEXT NULL,

	'Height' REAL NULL,

	'Building_ID' INTEGER NULL,

	CONSTRAINT 'FK_Building_Tree' FOREIGN KEY ('Building_ID') REFERENCES 'Building' ('Building_ID') ON DELETE No Action ON UPDATE No Action

)

;

SELECT AddGeometryColumn('Building', 'geometry', 4326, 'POLYGON');
SELECT AddGeometryColumn('HousePipe', 'geometry', 4326, 'LINESTRING');
SELECT AddGeometryColumn('Tree', 'geometry', 4326, 'POINT');
